apiVersion: apps/v1 
kind: Deployment
metadata:
  name: brandinquirer
  labels:
    server: brandinquirer
spec:
  selector:
    matchLabels:
      server: brandinquirer
  replicas: 1
  template: 
    metadata:
      labels:
        server: brandinquirer
    spec:
      containers:
        - name: brandinquirer
          image: docker-registry.icarcloud.net:8088/ztercel/brandinquirer:v1.0.0
          ports:
            - containerPort: 3000
        
---

apiVersion: v1
kind: Service
metadata:
  name: brandinquirer
  labels:
    server: brandinquirer
spec:
  selector:
    server: brandinquirer
  type: NodePort
  # clusterIP: 10.106.100.2
  ports:
    - name: http
      protocol: TCP
      nodePort: 32000
      port: 9000
      targetPort: 3000
